services:
  mongodb:
    image: mongo:latest
    container_name: ssuspy-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_USERNAME
      - MONGO_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/init.js
      - mongo-data:/data/db
    healthcheck:
      test: mongosh --quiet --eval "db.getSiblingDB('ssuspy')"
      interval: 10s
      timeout: 1s
      retries: 10

  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 1s
      retries: 10

  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      - TELEGRAM_API_ID
      - TELEGRAM_API_HASH
      - TELEGRAM_LOCAL=true
      - TELEGRAM_STAT=true
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    expose:
      - "8081:8081"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--output-document=/dev/null",
          "http://127.0.0.1:8082",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  bot:
    restart: unless-stopped
    container_name: ssuspy-bot
    build: ./
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USERNAME
      - MONGO_PASSWORD
      - MONGO_DB
      - DEV_MODE
      - REDIS_HOST=redis
      - REDIS_USERNAME
      - REDIS_PASSWORD
      - REDIS_PORT
      - REDIS_DB
      - TELEGRAM_TOKEN
      - TELEGRAM_API_URL
      - GITHUB_URL
    volumes:
      - ./locales:/home/appuser/app/locales
      - telegram-bot-api-data:/var/lib/telegram-bot-api/
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      telegram-bot-api:
        condition: service_healthy

volumes:
  telegram-bot-api-data:
  redis-data:
  mongo-data:
